### ISSUE TITLE
the latest LCL PY_GUI.EXE GETS DETECTED AS VIRUS ON WIN 11

### ISSUE THREAD

**Issue by 2019Z2** [Aetopia/LCLPy#7]
hi,
recently i wanted to install version 1.2.1 of the "LCLPy_GUI.exe" but windows defender recognised some of the files as **trojan**.

"Trojan:Win32/Wacatac.B!ml"

**Comment by 2019Z2** [comment]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.B!ml&threatid=2147735505

**Comment by Aetopia** [comment]
Sadly, this issue can't be fixed.
Its a problem with the antivirus not LCLPy.
